server:
  port: 82
#  1.大小写敏感
#  2.属性层级关系使用多行描述，每行结尾使用冒号结束
#  3.使用缩进表示层级关系，同层级左侧对齐，只允许使用空格（不允许使用Tab键）
#  4.属性值前面添加空格（属性名与属性值之间使用冒号+空格作为分隔）
#  5.表示注释

# 以下这些配置到---之前的都属于不同的环境的公共配置
lesson: springboot

# enterpise.name
enterprise:
  name: itcast
  age: 16
  tel: 4006184000
  # 数组
  subject:
    - Java
    - 前端
    - 大数据